### ISSUE TITLE
[16] imposible to asign subjects to a course

### ISSUE THREAD

**Issue by fgarcia-humanoide** [openeducat/openeducat_erp#702]
In the courses screen it is impossible to assign subjects. There are subjets but is imposible to add.
In this state the app is useless

![courses](https://github.com/openeducat/openeducat_erp/assets/7599709/b9266184-aa5a-4934-bf31-bbdf9d39c355)

**Comment by parthivgls** [comment]
fixed with https://github.com/openeducat/openeducat_erp/pull/703

**Comment by fgarcia-humanoide** [comment]
After installing new code I still cannot add subjects to a course.
